version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure you have a Dockerfile in the project root to build the NestJS app
    image: my-nest-app:latest  # Tag the image explicitly
    restart: always
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017  # Connect to the MongoDB service in the Docker network
    ports:
      - "3000:3000"  # Expose your app on port 3000
    depends_on:
      - mongo  # Ensure the MongoDB service is ready before starting the app
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local