upstream myapp1 {
    server nest-app:3000;
    server nest-app2:3000;
    server nest-app3:3000;
}

server {
    listen 8080;

    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/example.crt;
    ssl_certificate_key /etc/nginx/ssl/example.key;

    location / {
        proxy_pass http://myapp1;
    }
}

# server {
#     listen 3000;
#     location / {
#         proxy_pass http://nest-app:3000;
#     }

# }